### PR TITLE
use quill new api register(modules/) replace registerModules()

### PR DESCRIPTION
**Pull request by Justinidlerz**
new Quill Api have not registerModule alternatives is register

### CODE REVIEW

**Comment by irahopkinson** [comment]
Any chance this PR will be merged?

I'm currently using the fork because this repo doesn't work without the PR.

**Comment by cmbankester** [comment]
@Justinidlerz @irahopkinson Sorry for the delay. I'll test this out and merge it in ASAP!

**Comment by irahopkinson** [comment]
@cmbankester thanks for the quick response.

Will you be publishing the new version 0.3.0 with the merged changes to npm?

**Comment by cmbankester** [comment]
@irahopkinson I just did. Sorry, it's been a while since I've updated this one, and I don't really maintain it very well anymore.

**Comment by irahopkinson** [comment]
@cmbankester thanks again.

**Pull request merged**
